export const NOTIFICATION_EVENT_TYPES = {
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_DELETED: 'TASK_DELETED',
  TASK_COMMENT: 'TASK_COMMENT',
  CASE_COMMENT: 'CASE_COMMENT',
  CASE_NOTE: 'CASE_NOTE',
  TIME_ENTRY: 'TIME_ENTRY',
  EMAIL: 'EMAIL',
  MEETING: 'MEETING',
  DOCUMENT: 'DOCUMENT',
  GENERAL: 'GENERAL',
};

export const DEFAULT_NOTIFICATION_PAGE_SIZE = 20;










